# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PizzaTracker' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PizzaTracker
  pod 'DeepstreamIO', :podspec => '/Users/ahussein/Developer/deepstream.io-client-ios/DeepstreamIO.podspec'

end
